WordsCount/Models/Counter.cs
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace WordsCount.Models
{
    public static class Counter
    {
        private static readonly WordList english = new WordList();
        private static readonly WordList chinese = new WordList();
        private static readonly WordList hindi = new WordList();

        public static bool Any(string value, UnicodeCategory category) =>
            !string.IsNullOrWhiteSpace(value)
            && value.Any(@char => char.GetUnicodeCategory(@char) == category);

        public static void Add(string context) {
            var sb = new StringBuilder();

            foreach (char c in context)
            {
                if (char.IsLetter(c))
                    if (c >= 0x4E00 && c <= 0x9FEF)
                        chinese.AddWord(c.ToString());
                    else
                        sb.Append(c);
                else
                    sb.Append(' ');
            }

            context = sb.ToString();
            string[] list = context.Split(' ');

            foreach (string word in list)
            {
                if (word == " " || word == "")
                    continue;

                if (Any(word, UnicodeCategory.OtherLetter))
                {
                    hindi.AddWord(word);
                } else {
                    string w = word.ToLower();
                    english.AddWord(w);
                }
            }
        }

        public static IEnumerable<Word> GetEnglish(int limit) {
            return english.GetWords(limit);
        }

        public static IEnumerable<Word> GetChinese(int limit)
        {
            return chinese.GetWords(limit);
        }

        public static IEnumerable<Word> GetHindi(int limit)
        {
            return hindi.GetWords(limit);
        }

    }
}

WordsCount/Models/ErrorViewModel.cs
namespace WordsCount.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WordsCount/Models/Word.cs
using System;
namespace WordsCount.Models
{
    public class Word : IComparable<Word>
    {
        public string key { get; }
        public int value { get; set; }

        public Word(string key)
        {
            this.key = key;
            this.value = 0;
        }

        public void Add()
        {
            this.value++;
        }

        public int CompareTo(Word other)
        {
            if (this.value == other.value)
                return string.Compare(this.key, other.key, StringComparison.Ordinal);
            else
                return other.value.CompareTo(this.value);
        }
    }
}

WordsCount/Models/WordList.cs
using System.Collections.Generic;
using System.Linq;

namespace WordsCount.Models
{
    public class WordList
    {
        private Dictionary<string, Word> dictionary = new Dictionary<string, Word>();

        public void AddWord(string w)
        {
            Word word = dictionary.GetValueOrDefault<string, Word>(w, new Word(w));
            word.Add();
            dictionary[w] = word;
        }

        public List<Word> GetWords(int limit)
        {
            List<Word> words = dictionary.Values.ToList();
            words.Sort();
            if (limit == 0)
                return words;
            else
                return words.Take(limit).ToList();
        }
    }
}

WordsCount/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WordsCount.Models;

namespace WordsCount.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(string context)
        {
            if(context!=null)
                Counter.Add(context);
            return View();
        }

        public IActionResult English()
        {
            return View();
        }

        public IActionResult Chinese()
        {
            return View();
        }

        public IActionResult Hindi()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WordsCount/ViewComponents/WordListViewComponent.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using WordsCount.Models;
using Microsoft.AspNetCore.Mvc;

namespace WordsCount.ViewComponents
{
    public class WordListViewComponent: ViewComponent
    {
        public WordListViewComponent()
        {
        }

        public async Task<IViewComponentResult> InvokeAsync(int language, int limit)
        {
            var words = await GetWordsAsync(language, limit);
            return View(words);
        }

        private Task<IEnumerable<Word>> GetWordsAsync(int language, int limit)
        {
            return Task.FromResult(GetWords(language, limit));
        }

        private IEnumerable<Word> GetWords(int language, int limit)
        {
            switch (language) {
                case 1: 
                    return Counter.GetEnglish(limit);
                case 2: 
                    return Counter.GetChinese(limit);
                case 3: 
                    return Counter.GetHindi(limit);
                default:
                    return Counter.GetEnglish(limit);
            }

        }
    }
}

WordsCount/Views/Home/Chinese.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>Chinese Characters:</h3>
<div>
    @await Component.InvokeAsync("WordList", new { language = 2, limit = 0 })
</div>

WordsCount/Views/Home/Components/WordList/Default.cshtml
@model IEnumerable<WordsCount.Models.Word>

<table class="table">
    <thead>
        <tr class="table-primary">
            <th scope="col">Words</th>
            <th scope="col">Count</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var p in Model)
    {
        <tr>
            <th scope="row">@p.key</th>
            <td >@p.value</td>
        </tr>
    }
    </tbody>
</table>

WordsCount/Views/Home/English.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>English Words:</h3>
<div>
    @await Component.InvokeAsync("WordList", new { language = 1, limit = 0 })
</div>

WordsCount/Views/Home/Hindi.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h3>Hindi Words:</h3>
<div>
    @await Component.InvokeAsync("WordList", new { language = 3, limit = 0 })
</div>

WordsCount/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style type="text/css">
    #table {
        margin: 0 auto
    }
</style>

<div class="text-center">
    <h1 class="display-4">Words Count</h1>

    <div style="width:750px;margin:0 auto">
        <form method="post">
            <div class="form-group">
                <label for="context" class="float-left">Your Context: </label>
                <textarea required="required" class="form-control" id="context" rows="10" cols="90" name="context" placeholder="Your context goes here"></textarea>
                <br/>
                <button type="submit" class="btn btn-primary float-right">Submit</button>            
            </div>
        </form>
    </div>

    <div class="container" style="width:780px;margin-top:50px">
        <div class="row">
            <div class="col-sm">
                <p>Top English Words:</p>
                <div>
                    @await Component.InvokeAsync("WordList", new { language = 1, limit = 5 })
                </div>
                <a href="home/English">More</a>
            </div>
            <div class="col-sm">
                <p>Top Chinese Characters:</p>
                <div>
                    @await Component.InvokeAsync("WordList", new { language = 2, limit = 5 })
                </div>
                <a href="home/Chinese">More</a>
            </div>
            <div class="col-sm">
                <p>Top Hindi Words:</p>
                <div>
                    @await Component.InvokeAsync("WordList", new { language = 3, limit = 5 })
                </div>
                <a href="home/Hindi">More</a>
            </div>
        </div>
    </div>
</div>


WordsCount/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WordsCount</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE=" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/general.css" />
</head>
    <body>
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container">
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WordsCount</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <div class="container">
            <partial name="_CookieConsentPartial" />
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2019 - WordsCount - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
            </script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
            </script>
        </environment>
        <script src="~/js/site.js" asp-append-version="true"></script>

        @RenderSection("Scripts", required: false)
    </body>
</html>